# Generated by Django 3.0.5 on 2020-05-26 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200526_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likesmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='posts.Post'),
        ),
    ]
