# Generated by Django 3.0.5 on 2020-05-26 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200521_2330'),
        ('posts', '0003_auto_20200526_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.RemoveField(
            model_name='likesmodel',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='likesmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='likesmodel',
            name='user',
            field=models.ManyToManyField(to='accounts.Profile'),
        ),
        migrations.CreateModel(
            name='DislikesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_dislikes', to='posts.Post')),
                ('user', models.ManyToManyField(to='accounts.Profile')),
            ],
        ),
    ]
