# Generated by Django 3.0.5 on 2020-05-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200521_2330'),
        ('posts', '0004_auto_20200526_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likesmodel',
            name='user',
            field=models.ManyToManyField(related_name='user_likes', to='accounts.Profile'),
        ),
    ]
