# Generated by Django 3.0.5 on 2020-05-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200521_2330'),
        ('posts', '0005_auto_20200526_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislikesmodel',
            name='user',
            field=models.ManyToManyField(related_name='user_dislikes', to='accounts.Profile'),
        ),
    ]
