# Generated by Django 3.0.5 on 2020-05-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200521_2330'),
        ('posts', '0006_auto_20200527_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislikesmodel',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user_dislikes', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='likesmodel',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user_likes', to='accounts.Profile'),
        ),
    ]
