export const LIKE_API_START = "LIKE_API_START"
export const LOAD_LIKES = "LOAD_LIKES"
export const ADD_LIKE = "ADD_LIKE"
export const REMOVE_LIKE = "REMOVE_LIKE"
export const DISLIKE_POST = "DISLIKE_POST"
