export const POST_API_START = "POST_API_START"
export const ADD_POST = "ADD_POST"
export const LOAD_POSTS = "LOAD_POSTS"
export const DELETE_POST = "DELETE_POST"
export const LIKE_POST = "LIKE_POST"
export const DISLIKE_POST = "DISLIKE_POST"
