# Generated by Django 3.0.5 on 2020-05-15 20:51

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=5000)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('facebook_link', models.URLField()),
                ('linkedin_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('website', models.URLField()),
                ('instagram_link', models.URLField()),
                ('github_link', models.URLField()),
                ('professional_status', models.CharField(choices=[('DEV', 'Developer'), ('JNR_DEV', 'Junior Developer'), ('SNR_DEV', 'Senior Developer'), ('INT', 'Intern'), ('MAN', 'Manager'), ('STU_LEA', 'Student or Learning'), ('INS_TEA', 'Instructor or Teacher'), ('OTH', 'Other')], default='OTH', max_length=7)),
                ('location', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=400)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True)),
                ('is_current', models.BooleanField()),
                ('desc', models.CharField(max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_experience', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sch_name', models.CharField(max_length=400)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True)),
                ('is_current', models.BooleanField()),
                ('desc', models.CharField(max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_education', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
    ]
