# Generated by Django 3.0.5 on 2020-05-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200515_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
