# Generated by Django 3.0.5 on 2020-05-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200519_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
