export const LOAD_EDUCATION_START = "LOAD_EDUCATION_START"
export const LOAD_EDUCATIONS = "LOAD_EDUCATIONS"
export const ADD_EDUCATION = "ADD_EDUCATION"
export const LOAD_USER_EDUCATIONS = "LOAD_USER_EDUCATIONS"
