import React from "react"

function LoadingPage() {
  return (
    <>
      <div className="container text-center h-screen flex justify-center items-center flex-col padding-top ">
        <div className="loadingio-spinner-pulse-743pldfgp5c">
          <div className="ldio-gg9rmic51kb">
            <div></div>
            <div></div>
            <div></div>
          </div>
        </div>
      </div>

      <style jsx>
        {`
          .flex {
            display: flex;
          }
          .h-screen {
            max-height: 100vh;
          }
          .justify-center {
            justify-content: center;
          }
          .items-center {
            align-items: center;
          }
          .flex-col {
            flex-direction: column;
          }
          .padding-top {
            padding-top: 4rem;
          }
          @keyframes ldio-gg9rmic51kb-1 {
            0% {
              top: 36px;
              height: 128px;
            }
            50% {
              top: 60px;
              height: 80px;
            }
            100% {
              top: 60px;
              height: 80px;
            }
          }
          @keyframes ldio-gg9rmic51kb-2 {
            0% {
              top: 41.99999999999999px;
              height: 116.00000000000001px;
            }
            50% {
              top: 60px;
              height: 80px;
            }
            100% {
              top: 60px;
              height: 80px;
            }
          }
          @keyframes ldio-gg9rmic51kb-3 {
            0% {
              top: 48px;
              height: 104px;
            }
            50% {
              top: 60px;
              height: 80px;
            }
            100% {
              top: 60px;
              height: 80px;
            }
          }
          .ldio-gg9rmic51kb div {
            position: absolute;
            width: 30px;
          }
          .ldio-gg9rmic51kb div:nth-child(1) {
            left: 35px;
            background: #17a2b8;
            animation: ldio-gg9rmic51kb-1 1s cubic-bezier(0, 0.5, 0.5, 1)
              infinite;
            animation-delay: -0.2s;
          }
          .ldio-gg9rmic51kb div:nth-child(2) {
            left: 85px;
            background: #73ecff;
            animation: ldio-gg9rmic51kb-2 1s cubic-bezier(0, 0.5, 0.5, 1)
              infinite;
            animation-delay: -0.1s;
          }
          .ldio-gg9rmic51kb div:nth-child(3) {
            left: 135px;
            background: #d4e3e5;
            animation: ldio-gg9rmic51kb-3 1s cubic-bezier(0, 0.5, 0.5, 1)
              infinite;
            animation-delay: undefineds;
          }

          .loadingio-spinner-pulse-743pldfgp5c {
            width: 200px;
            height: 200px;
            display: inline-block;
            overflow: hidden;
            background: #ffffff;
          }
          .ldio-gg9rmic51kb {
            width: 100%;
            height: 100%;
            position: relative;
            transform: translateZ(0) scale(1);
            backface-visibility: hidden;
            transform-origin: 0 0; /* see note above */
          }
          .ldio-gg9rmic51kb div {
            box-sizing: content-box;
          }
          /* generated by https://loading.io/ */
        `}
      </style>
    </>
  )
}

export default LoadingPage
